//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Klienci()
        {
            this.Wypozyczenia = new ObservableCollection<Wypozyczenia>();
        }
    
        public int id_klienta { get; set; }
        public string pesel { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public Nullable<System.DateTime> data_urodzenia { get; set; }
        public string nr_telefonu { get; set; }
        public string kraj { get; set; }
        public string miasto { get; set; }
        public string ulica { get; set; }
        public string numer_domu { get; set; }
        public string numer_lokalu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
