//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MalinowskyCarRentalEntities : DbContext
    {
        public MalinowskyCarRentalEntities()
            : base("name=MalinowskyCarRentalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bazy> Bazy { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Modele_samochodow> Modele_samochodow { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Rodzaje_paliwa> Rodzaje_paliwa { get; set; }
        public virtual DbSet<Samochody> Samochody { get; set; }
        public virtual DbSet<Stany_samochodu> Stany_samochodu { get; set; }
        public virtual DbSet<Typy_nadwozia> Typy_nadwozia { get; set; }
        public virtual DbSet<Typy_samochodow> Typy_samochodow { get; set; }
        public virtual DbSet<Wersje_modeli> Wersje_modeli { get; set; }
        public virtual DbSet<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
