//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Samochody
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Samochody()
        {
            this.Wypozyczenia = new ObservableCollection<Wypozyczenia>();
        }
    
        public int id_samochodu { get; set; }
        public Nullable<int> id_typu { get; set; }
        public Nullable<int> id_bazy { get; set; }
        public Nullable<int> id_stanu_samochodu { get; set; }
        public string vin { get; set; }
        public Nullable<int> przebieg { get; set; }
        public Nullable<short> cena_za_dzien { get; set; }
    
        public virtual Bazy Bazy { get; set; }
        public virtual Stany_samochodu Stany_samochodu { get; set; }
        public virtual Typy_samochodow Typy_samochodow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Wypozyczenia> Wypozyczenia { get; set; }
    }
}
