//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Typy_samochodow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Typy_samochodow()
        {
            this.Samochody = new ObservableCollection<Samochody>();
        }
    
        public int id_typu { get; set; }
        public Nullable<int> id_wersji { get; set; }
        public Nullable<short> rok_produkcji { get; set; }
        public string kolor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Samochody> Samochody { get; set; }
        public virtual Wersje_modeli Wersje_modeli { get; set; }
    }
}
