//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Wersje_modeli
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Wersje_modeli()
        {
            this.Typy_samochodow = new ObservableCollection<Typy_samochodow>();
        }
    
        public int id_wersji { get; set; }
        public Nullable<int> id_modelu { get; set; }
        public Nullable<int> id_paliwa { get; set; }
        public Nullable<int> id_typu_nadwozia { get; set; }
        public Nullable<short> moc_kw { get; set; }
        public Nullable<short> pojemnosc_silnika { get; set; }
        public Nullable<byte> liczba_miejsc { get; set; }
    
        public virtual Modele_samochodow Modele_samochodow { get; set; }
        public virtual Rodzaje_paliwa Rodzaje_paliwa { get; set; }
        public virtual Typy_nadwozia Typy_nadwozia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<Typy_samochodow> Typy_samochodow { get; set; }
    }
}
