//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MalinowskyCarRental
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Wypozyczenia
    {
        public int id_wypozyczenia { get; set; }
        public Nullable<int> id_klienta { get; set; }
        public Nullable<int> id_pracownika { get; set; }
        public Nullable<int> id_samochodu { get; set; }
        public System.DateTime data_wypozyczenia { get; set; }
        public System.DateTime planowana_data_zwrotu { get; set; }
        public Nullable<System.DateTime> data_zwrotu { get; set; }
        public Nullable<int> oplata_dodatkowa { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
        public virtual Samochody Samochody { get; set; }
    }
}
